apiVersion: apps/v1
kind: Deployment
metadata:
  name: snake-game
  namespace: snake-game
  labels:
    app: snake-game
spec:
  revisionHistoryLimit: 1
  replicas: 1
  selector:
    matchLabels:
      app: snake-game
  template:
    metadata:
      labels:
        app: snake-game
    spec:
      containers:
      - name: snake-game
        image: docker.io/lavalex/snake-game:2f804efe7c998f6fc12770156089c997ad5c0e62
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          protocol: TCP
        env:
        - name: PORT
          value: "8080"
        - name: DB_HOST
          value: postgres
        - name: DB_PORT
          value: "5432"
        - name: DB_SSLMODE
          value: disable
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: postgres-credentials
              key: POSTGRES_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-credentials
              key: POSTGRES_PASSWORD
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: postgres-credentials
              key: POSTGRES_DB
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
      initContainers:
      - name: wait-for-postgres
        image: docker.io/lavalex/snake-game:2f804efe7c998f6fc12770156089c997ad5c0e62
        command:
          - sh
          - -c
          - |
            echo "Waiting for postgres..."
            # Using timeout and nc (netcat) which is common in many base images
            # or a simple bash socket check
            until nc -z postgres 5432; do
              echo "Waiting for postgres..."
              sleep 2
            done
