apiVersion: observability.openshift.io/v1
kind: ClusterLogForwarder
metadata:
  name: snake-game-logger
  namespace: openshift-logging
#  annotations:
#    observability.openshift.io/log-level: debug
spec:
  filters:
    - name: detect-multiline
      type: detectMultilineException
  outputs:
    - name: loki-output
      type: lokiStack
      lokiStack:
        target:
          name: logging-loki
          namespace: openshift-logging
        authentication:
          token:
            from: secret
            secret:
              name: loki-token-secret  # Secret containing the token
              key: token
      tls:
        ca:
          key: service-ca.crt
          configMapName: openshift-service-ca.crt
      # Delivery Tuning
      tuning:
        delivery: AtLeastOnce
        rateLimitPerSecond: 500    
  inputs:
    - name: snake-game-logs
      type: application
      application:
        includes:
          - namespace: snake-game  # Restrict to snake-game namespace
  pipelines:
    - name: forward-snake-game-to-loki
      inputRefs:
        - snake-game-logs
      outputRefs:
        - loki-output 
      filterRefs:
        - detect-multiline
  collector:
    type: vector
  serviceAccount:
    name: logcollector

