{
 "title": "Snake Game",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Highest Score",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "snake_high_score", "legendFormat": "{{player_name}}" }
   ]
  },
  {
   "title": "Apples Eaten",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(snake_apples_eaten_total)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Players Games",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 9, "x": 11, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "snake_player_games_total", "legendFormat": "{{player_name}}" }
   ]
  },
  {
   "title": "Game logs",
   "type": "logs",
   "gridPos": { "h": 10, "w": 20, "x": 0, "y": 8 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{ kubernetes_namespace_name=\"snake-game\" } | json | line_format \"{{.message}}\""
    }
   ]
  }
 ]
}